### ISSUE TITLE
removes thoses exports and referenced variables

### ISSUE THREAD

**Issue by snakeUni** [egoist/babel-plugin-eliminator#1]
sorry, I am confused about this code

options

```
{
  "plugins": [
    ["eliminator", {"namedExports": ["foo"]}]
  ]
}
```

input

```
import pkg from 'some-pkg'

const someVariable = 'some-string'

export const foo = () => {
    return pkg(someVariable)
}
```

output

```
export var foo = 1
```

this plugin it essentially removes thoses exports and referenced variables. why does foo exist in output other than remove it?

**Comment by egoist** [comment]
cause sometimes you might need to know if the file has certain exports, I'll add an option to allow completely removing the code if that's the use case.
